<?
	//include module
	\Bitrix\Main\Loader::includeModule("dw.deluxe");

	//vars
	$catalogIblockId = null;
	$arPriceCodes = array();

	//get template settings
	$arTemplateSettings = DwSettings::getInstance()->getCurrentSettings();
	if(!empty($arTemplateSettings)){
		$catalogIblockId = $arTemplateSettings["TEMPLATE_PRODUCT_IBLOCK_ID"];
		$arPriceCodes = explode(", ", $arTemplateSettings["TEMPLATE_PRICE_CODES"]);
	}
?>
<?$APPLICATION->IncludeComponent(
	"dresscode:search.line", 
	"version3", 
	array(
		"COMPONENT_TEMPLATE" => "version3",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "15",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"PRICE_CODE" => array(
		),
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"PROPERTY_CODE" => array(
			0 => "ATT_BRAND",
			1 => "USER_ID",
			2 => "BLOG_POST_ID",
			3 => "MORE_PROPERTIES",
			4 => "BLOG_COMMENTS_CNT",
			5 => "VOTE_COUNT",
			6 => "SHOW_MENU",
			7 => "SIMILAR_PRODUCT",
			8 => "RATING",
			9 => "RELATED_PRODUCT",
			10 => "VOTE_SUM",
			11 => "CML2_ARTICLE",
			12 => "VIDEO",
			13 => "WARRANTY",
			14 => "DELIVERY",
			15 => "COLLECTION",
			16 => "OFFERS",
			17 => "PICKUP",
			18 => "REF",
			19 => "COLOR",
			20 => "ZOOM2",
			21 => "BATTERY_LIFE",
			22 => "SWITCH",
			23 => "GRAF_PROC",
			24 => "LENGTH_OF_CORD",
			25 => "DISPLAY",
			26 => "LOADING_LAUNDRY",
			27 => "FULL_HD_VIDEO_RECORD",
			28 => "INTERFACE",
			29 => "COMPRESSORS",
			30 => "Number_of_Outlets",
			31 => "MAX_RESOLUTION_VIDEO",
			32 => "MAX_BUS_FREQUENCY",
			33 => "MAX_RESOLUTION",
			34 => "FREEZER",
			35 => "POWER_SUB",
			36 => "POWER",
			37 => "HARD_DRIVE_SPACE",
			38 => "MEMORY",
			39 => "OS",
			40 => "ZOOM",
			41 => "PAPER_FEED",
			42 => "SUPPORTED_STANDARTS",
			43 => "VIDEO_FORMAT",
			44 => "SUPPORT_2SIM",
			45 => "MP3",
			46 => "ETHERNET_PORTS",
			47 => "MATRIX",
			48 => "CAMERA",
			49 => "PHOTOSENSITIVITY",
			50 => "DEFROST",
			51 => "SPEED_WIFI",
			52 => "SPIN_SPEED",
			53 => "PRINT_SPEED",
			54 => "SOCKET",
			55 => "IMAGE_STABILIZER",
			56 => "GSM",
			57 => "SIM",
			58 => "TYPE",
			59 => "MEMORY_CARD",
			60 => "TYPE_BODY",
			61 => "TYPE_MOUSE",
			62 => "TYPE_PRINT",
			63 => "CONNECTION",
			64 => "TYPE_OF_CONTROL",
			65 => "TYPE_DISPLAY",
			66 => "TYPE2",
			67 => "REFRESH_RATE",
			68 => "RANGE",
			69 => "AMOUNT_MEMORY",
			70 => "MEMORY_CAPACITY",
			71 => "VIDEO_BRAND",
			72 => "DIAGONAL",
			73 => "RESOLUTION",
			74 => "TOUCH",
			75 => "CORES",
			76 => "LINE_PROC",
			77 => "PROCESSOR",
			78 => "CLOCK_SPEED",
			79 => "TYPE_PROCESSOR",
			80 => "PROCESSOR_SPEED",
			81 => "HARD_DRIVE",
			82 => "HARD_DRIVE_TYPE",
			83 => "Number_of_memory_slots",
			84 => "MAXIMUM_MEMORY_FREQUENCY",
			85 => "TYPE_MEMORY",
			86 => "BLUETOOTH",
			87 => "FM",
			88 => "GPS",
			89 => "HDMI",
			90 => "SMART_TV",
			91 => "USB",
			92 => "WIFI",
			93 => "FLASH",
			94 => "ROTARY_DISPLAY",
			95 => "SUPPORT_3D",
			96 => "SUPPORT_3G",
			97 => "WITH_COOLER",
			98 => "FINGERPRINT",
			99 => "TOTAL_OUTPUT_POWER",
			100 => "VID_ZASTECHKI",
			101 => "VID_SUMKI",
			102 => "PROFILE",
			103 => "VYSOTA_RUCHEK",
			104 => "GAS_CONTROL",
			105 => "GRILL",
			106 => "GENRE",
			107 => "OTSEKOV",
			108 => "CONVECTION",
			109 => "INTAKE_POWER",
			110 => "NAZNAZHENIE",
			111 => "BULK",
			112 => "PODKLADKA",
			113 => "SURFACE_COATING",
			114 => "brand_tyres",
			115 => "SEASON",
			116 => "SEASONOST",
			117 => "DUST_COLLECTION",
			118 => "COUNTRY_BRAND",
			119 => "DRYING",
			120 => "REMOVABLE_TOP_COVER",
			121 => "CONTROL",
			122 => "FINE_FILTER",
			123 => "FORM_FAKTOR",
			124 => "SKU_COLOR",
			125 => "",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_MEASURES" => "N",
		"CONVERT_CASE" => "N",
		"STEMMING" => "N",
		"LAZY_LOAD_PICTURES" => "N"
	),
	false
);?>