<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Распродажа");?><h1>Распродажа</h1>
<?
	//include module
	\Bitrix\Main\Loader::includeModule("dw.deluxe");

	//vars
	$catalogIblockId = null;
	$arPriceCodes = array();

	//get template settings
	$arTemplateSettings = DwSettings::getInstance()->getCurrentSettings();
	if(!empty($arTemplateSettings)){
		$catalogIblockId = $arTemplateSettings["TEMPLATE_PRODUCT_IBLOCK_ID"];
		$arPriceCodes = explode(", ", $arTemplateSettings["TEMPLATE_PRICE_CODES"]);
	}
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:menu", 
	"personal", 
	array(
		"COMPONENT_TEMPLATE" => "personal",
		"ROOT_MENU_TYPE" => "left2",
		"MENU_CACHE_TYPE" => "A",
		"MENU_CACHE_TIME" => "3600000",
		"MENU_CACHE_USE_GROUPS" => "Y",
		"MENU_CACHE_GET_VARS" => array(
		),
		"MAX_LEVEL" => "1",
		"CHILD_MENU_TYPE" => "",
		"USE_EXT" => "N",
		"DELAY" => "N",
		"ALLOW_MULTI_SELECT" => "N"
	),
	false
);?><?$APPLICATION->IncludeComponent(
	"dresscode:simple.offers", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "15",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"PROP_NAME" => "OFFERS",
		"PROP_VALUE" => "11",
		"CONVERT_CURRENCY" => "Y",
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "COLOR",
			2 => "ZOOM2",
			3 => "BATTERY_LIFE",
			4 => "SWITCH",
			5 => "GRAF_PROC",
			6 => "LENGTH_OF_CORD",
			7 => "DISPLAY",
			8 => "LOADING_LAUNDRY",
			9 => "FULL_HD_VIDEO_RECORD",
			10 => "INTERFACE",
			11 => "COMPRESSORS",
			12 => "Number_of_Outlets",
			13 => "MAX_RESOLUTION_VIDEO",
			14 => "MAX_BUS_FREQUENCY",
			15 => "MAX_RESOLUTION",
			16 => "FREEZER",
			17 => "POWER_SUB",
			18 => "POWER",
			19 => "HARD_DRIVE_SPACE",
			20 => "MEMORY",
			21 => "OS",
			22 => "ZOOM",
			23 => "PAPER_FEED",
			24 => "SUPPORTED_STANDARTS",
			25 => "VIDEO_FORMAT",
			26 => "SUPPORT_2SIM",
			27 => "MP3",
			28 => "ETHERNET_PORTS",
			29 => "MATRIX",
			30 => "CAMERA",
			31 => "PHOTOSENSITIVITY",
			32 => "DEFROST",
			33 => "SPEED_WIFI",
			34 => "SPIN_SPEED",
			35 => "PRINT_SPEED",
			36 => "SOCKET",
			37 => "IMAGE_STABILIZER",
			38 => "GSM",
			39 => "SIM",
			40 => "TYPE",
			41 => "MEMORY_CARD",
			42 => "TYPE_BODY",
			43 => "TYPE_MOUSE",
			44 => "TYPE_PRINT",
			45 => "CONNECTION",
			46 => "TYPE_OF_CONTROL",
			47 => "TYPE_DISPLAY",
			48 => "TYPE2",
			49 => "REFRESH_RATE",
			50 => "RANGE",
			51 => "AMOUNT_MEMORY",
			52 => "MEMORY_CAPACITY",
			53 => "VIDEO_BRAND",
			54 => "DIAGONAL",
			55 => "RESOLUTION",
			56 => "TOUCH",
			57 => "CORES",
			58 => "LINE_PROC",
			59 => "PROCESSOR",
			60 => "CLOCK_SPEED",
			61 => "TYPE_PROCESSOR",
			62 => "PROCESSOR_SPEED",
			63 => "HARD_DRIVE",
			64 => "HARD_DRIVE_TYPE",
			65 => "Number_of_memory_slots",
			66 => "MAXIMUM_MEMORY_FREQUENCY",
			67 => "TYPE_MEMORY",
			68 => "BLUETOOTH",
			69 => "FM",
			70 => "GPS",
			71 => "HDMI",
			72 => "SMART_TV",
			73 => "USB",
			74 => "WIFI",
			75 => "FLASH",
			76 => "ROTARY_DISPLAY",
			77 => "SUPPORT_3D",
			78 => "SUPPORT_3G",
			79 => "WITH_COOLER",
			80 => "FINGERPRINT",
			81 => "TOTAL_OUTPUT_POWER",
			82 => "HTML",
			83 => "VID_ZASTECHKI",
			84 => "VID_SUMKI",
			85 => "PROFILE",
			86 => "VYSOTA_RUCHEK",
			87 => "GAS_CONTROL",
			88 => "GRILL",
			89 => "MORE_PROPERTIES",
			90 => "GENRE",
			91 => "OTSEKOV",
			92 => "CONVECTION",
			93 => "INTAKE_POWER",
			94 => "NAZNAZHENIE",
			95 => "BULK",
			96 => "PODKLADKA",
			97 => "SURFACE_COATING",
			98 => "brand_tyres",
			99 => "SEASON",
			100 => "SEASONOST",
			101 => "DUST_COLLECTION",
			102 => "COUNTRY_BRAND",
			103 => "DRYING",
			104 => "REMOVABLE_TOP_COVER",
			105 => "CONTROL",
			106 => "FINE_FILTER",
			107 => "FORM_FAKTOR",
			108 => "SKU_COLOR",
			109 => "CML2_ARTICLE",
			110 => "MARKER_PHOTO",
			111 => "NEW",
			112 => "DELIVERY_DESC",
			113 => "SALE",
			114 => "MARKER",
			115 => "POPULAR",
			116 => "WEIGHT",
			117 => "HEIGHT",
			118 => "DEPTH",
			119 => "WIDTH",
			120 => "",
		),
		"CURRENCY_ID" => "RUB",
		"DISABLE_SELECT_CATEGORY" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_MEASURES" => "N",
		"FILTER_PRICE_CODE" => array(
			0 => "BASE",
		)
	),
	false,
	array(
		"ACTIVE_COMPONENT" => "Y"
	)
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>